# This config file for Travis CI
sudo: required
dist: trusty
language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

notifications:
  email:
    recipients:
      - levi.armstrong@swri.org

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
    - CMAKE_ARGS=-DENABLE_TESTS=ON
    - BUILD_PKGS_WHITELIST="trajopt trajopt_sco trajopt_tools trajopt_utils"

matrix:
  include:
    - env: ROS_DISTRO=melodic CLANG_FORMAT_CHECK=file CLANG_FORMAT_VERSION=8
    - env: ROS_DISTRO=kinetic
    - env: ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed
    - env: ROS_DISTRO=melodic ROS_PARALLEL_JOBS=-j4  # Travis was running out of resources and hanging for melodic builds
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed ROS_PARALLEL_JOBS=-j4
  allow_failures:
    - env: ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed ROS_PARALLEL_JOBS=-j4

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
