# This config file for Travis CI
sudo: required
dist: trusty
language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

notifications:
  email:
    recipients:
      - levi.armstrong@swri.org

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall

matrix:
  include:
    - env: ROS_DISTRO=kinetic CLANG_FORMAT_CHECK=file
      git:
        submodules: false
    - env: ROS_DISTRO=kinetic ROS_REPO=ros              NOT_TEST_INSTALL=true
    - env: ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed NOT_TEST_INSTALL=true
    - env: ROS_DISTRO=melodic ROS_REPO=ros              NOT_TEST_INSTALL=true
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed NOT_TEST_INSTALL=true

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
